GET http://localhost:54321/welcome

###
GET http://localhost:54321/user-service/health-check

###
POST http://localhost:8080/user-service/users
Content-Type: application/json

{
  "email": "kidd@gmail.com",
  "name": "Jay Lim",
  "pwd": "asdasd"
}

###
POST http://localhost:8080/user-service/users
Content-Type: application/json

{
  "email": "jason@gmail.com",
  "name": "Jason",
  "pwd": "asdasd"
}

###
GET http://localhost:54321/users

###
GET http://localhost:54321/user-service/message

###
GET http://localhost:8080/user-service/users

###
GET http://localhost:8080/user-service/users/f045e043-205c-4627-b87b-eb130e6de2c6
